package nz.co.sugbo4j.bike_components_scraper.batch;

import nz.co.sugbo4j.bike_components_scraper.config.RetailerConfiguration;
import nz.co.sugbo4j.bike_components_scraper.model.ScrapedProduct;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Component
public class ProductItemProcessor
        implements ItemProcessor<RetailerConfiguration.RetailerProperties.Product, ScrapedProduct> {

    @Override
    public ScrapedProduct process(RetailerConfiguration.RetailerProperties.Product item) throws Exception {
        // TODO: Implement actual processing logic to transform raw scraped data into
        // ScrapedProduct
        // For now, create a dummy ScrapedProduct
        System.out.println("Processing product: " + item.getCategory() + " - " + item.getUrl());
        return new ScrapedProduct(
                null, // ID will be generated by MongoDB
                "dummyRetailerId",
                "Dummy Retailer",
                "http://dummy.url/" + item.getUrl(),
                "Dummy Product " + item.getCategory(),
                "Dummy Brand",
                item.getCategory(),
                BigDecimal.valueOf(99.99),
                "NZD",
                "http://dummy.url/image.jpg",
                "This is a dummy product description.",
                LocalDateTime.now(),
                true);
    }
}